meta_product_name: "Paul Busby"
meta_title: "Paul Busby - Marketer & Developer"
meta_description: "I like building websites - let's get to know each other"
meta_image: "cover.png" # should exist in `app/assets/images/`
