meta_product_name: "Paul Busby"
meta_title: "Paul Busby - Marketing & Dev"
meta_description: "Your brand is my command. Let's get to know each other."
meta_image: "cover.png" # should exist in `app/assets/images/`
